from __future__ import annotations

MONTH_NAMES = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]
SIGNS = [
    "Aries",
    "Taurus",
    "Gemini",
    "Cancer",
    "Leo",
    "Virgo",
    "Libra",
    "Scorpio",
    "Sagittarius",
    "Capricorn",
    "Aquarius",
    "Pisces",
]
NAKSHATRAS = [
    "Ashwini",
    "Bharani",
    "Krittika",
    "Rohini",
    "Mrigashira",
    "Ardra",
    "Punarvasu",
    "Pushya",
    "Ashlesha",
    "Magha",
    "PurvaPhalguni",
    "UttaraPhalguni",
    "Hasta",
    "Chitra",
    "Swati",
    "Vishakha",
    "Anuradha",
    "Jyeshtha",
    "Mula",
    "PurvaAshadha",
    "UttaraAshadha",
    "Shravana",
    "Dhanishtha",
    "Shatabhisha",
    "PurvaBhadrapada",
    "UttaraBhadrapada",
    "Revati",
]
MUHURTA_PURPOSES = [
    ("marriage", "Marriage", "Matrimonio"),
    ("engagement", "Engagement", "Compromiso"),
    ("business_launch", "Business launch", "Lanzamiento de negocio"),
    ("company_registration", "Company registration", "Registro de empresa"),
    ("contract", "Signing a contract", "Firma de contrato"),
    ("commercial_agreement", "Commercial agreement", "Acuerdo comercial"),
    ("starting_new_job", "Starting a new job", "Inicio de un nuevo trabajo"),
    ("starting_project", "Starting a project", "Inicio de un proyecto"),
    ("studies", "Studies", "Estudios"),
    ("beginning_course", "Beginning a course", "Inicio de un curso"),
    ("spiritual_study", "Beginning spiritual study", "Inicio de estudio espiritual"),
    ("mantra", "Mantra initiation", "Iniciación de mantra"),
    ("puja", "Pūjā / ritual", "Pūjā / ritual"),
    ("home_entry", "Entering a new house", "Entrada a una casa"),
    ("office_entry", "Entering a new office", "Entrada a una oficina"),
    ("opening_shop", "Opening a shop", "Apertura de un comercio"),
    ("travel", "Travel", "Viaje"),
    ("surgery", "Surgery", "Cirugía"),
    ("medical_treatment", "Medical treatment", "Tratamiento médico"),
    ("buying_item", "Buying an important item", "Compra importante"),
    ("financial_activity", "Financial activity", "Actividad financiera"),
    ("debt_repayment", "Debt repayment", "Pago de deuda"),
    ("custom", "Custom purpose", "Propósito personalizado"),
]
